# Generated by Django 3.2.9 on 2022-01-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='first',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last',
            field=models.CharField(max_length=64),
        ),
    ]
